import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import { GetServerSideProps } from "next";
import { fetchCategories } from "@/http";
import { ICategory, ICollectionResponse } from "@/types";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1 className="text-primary-dark text-2xl font-bold">
                Hello from tailwind
            </h1>
        </>
    );
}

export const getServerSideProps: GetServerSideProps = async () => {
    // categories

    const {
        data: categories,
    }: AxiosResponse<ICollectionResponse<ICategory[]>> = fetchCategories;

    return {
        props: {
            categories: {
                items: [],
            },
        },
    };
};
